# Generated by cucumber-sinatra. (2014-10-06 13:21:07 +0100)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'app/bibiliodebabel.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = BDB

class BDBWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  BDBWorld.new
end
